### PR TITLE
add /bin/bash for Docker

### PR DESCRIPTION
**Pull request by yanhick**
Hi,
I've had to make the following change to make the setup script run within an Ubuntu Docker container.
I had the same error as #66, so I saw that you're already working on a fix. Just thought I let you know.

Thanks for the project, it works great !

### CODE REVIEW

**Comment by mietek** [comment]
Thanks. Can you show how are you running the setup script?

**Comment by mietek** [comment]
@yanhick: ping

**Comment by yanhick** [comment]
Sorry, i missed your previous message.

Here is the Dockerfile which fails on "halcyon install":
https://gist.github.com/yanhick/4996fcfe553b9fcd1cd2

2015-04-22 21:13 GMT+02:00 Miëtek Bak <notifications@github.com>:

**Comment by mietek** [comment]
Thanks. Please note the setup script was intended to be run within an existing GNU _bash_ shell, as shown in the [Halcyon installation instructions](https://halcyon.sh/#installation):
```
$ eval "$( curl -sL https://github.com/mietek/halcyon/raw/master/setup.sh )"
```

Your Dockerfile runs `apt-get`, clones the Halcyon repository, then marks the script as executable, and runs it in a new shell.  First, if this was the intended usage, the script would be already marked as executable in the repository.  Second, your already performing two out of the three setup script steps manually, so you might as well perform the third step (by creating the `/app` directory), and skip running the setup script altogether.

The setup script is due to be improved shortly.

**Pull request closed without merging**
